_BASE_: "../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: 
  - cityscapes_in_voc_train
  TEST: 
  - kitti
TEST:
  EVAL_PERIOD: 500
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.03
  STEPS: (2000, 2500)
  MAX_ITER: 1000
  WARMUP_ITERS: 100
  CLIP_GRADIENTS:
    ENABLED: True
  AMP:
    ENABLED: True