_BASE_: "../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 7
DATASETS:
  TRAIN: 
  - daytime_clear_train
  TEST: 
  - night_rainy_val
TEST:
  EVAL_PERIOD: 1000
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (2000, 2500)
  MAX_ITER: 3000
  WARMUP_ITERS: 100
  CLIP_GRADIENTS:
    ENABLED: True
  AMP:
    ENABLED: True