_BASE_: "../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: 
  - crowdhuman_train
  TEST: 
  - crowdhuman_val
TEST:
  EVAL_PERIOD: 1000
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (4000, 5000)
  MAX_ITER: 6000
  WARMUP_ITERS: 100
  CLIP_GRADIENTS:
    ENABLED: True
  AMP:
    ENABLED: True