_BASE_: ../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 4
DATASETS:
  TRAIN:
  - EgoHands_specific_shot5_seed30
  TEST:
  - EgoHands_specific_test
TEST:
  EVAL_PERIOD: 5
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (12000, 16000)
  MAX_ITER: 100
  WARMUP_ITERS: 25
  CLIP_GRADIENTS:
    ENABLED: true
  AMP:
    ENABLED: true
