_BASE_: ../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN:
  - pothole_shot10_seed30
  TEST:
  - pothole_test
TEST:
  EVAL_PERIOD: 2
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (12000, 16000)
  MAX_ITER: 50
  WARMUP_ITERS: 50
  CLIP_GRADIENTS:
    ENABLED: true
  AMP:
    ENABLED: true
