_BASE_: ../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 26
DATASETS:
  TRAIN:
  - AmericanSignLanguageLetters_shot3_seed30
  TEST:
  - AmericanSignLanguageLetters_test
TEST:
  EVAL_PERIOD: 19
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (12000, 16000)
  MAX_ITER: 390
  WARMUP_ITERS: 15
  CLIP_GRADIENTS:
    ENABLED: true
  AMP:
    ENABLED: true
