_BASE_: ../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 3
DATASETS:
  TRAIN:
  - BCCD_shot10_seed3
  TEST:
  - BCCD_test
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (12000, 16000)
  MAX_ITER: 30
  WARMUP_ITERS: 50
  CLIP_GRADIENTS:
    ENABLED: true
  AMP:
    ENABLED: true
