_BASE_: ../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN:
  - PascalVOC_shot3_seed3
  TEST:
  - PascalVOC_test
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (12000, 16000)
  MAX_ITER: 60
  WARMUP_ITERS: 15
  CLIP_GRADIENTS:
    ENABLED: true
  AMP:
    ENABLED: true
