_BASE_: ../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 36
DATASETS:
  TRAIN:
  - boggleBoards_shot3_seed30
  TEST:
  - boggleBoards_test
TEST:
  EVAL_PERIOD: 27
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (12000, 16000)
  MAX_ITER: 540
  WARMUP_ITERS: 15
  CLIP_GRADIENTS:
    ENABLED: true
  AMP:
    ENABLED: true
