_BASE_: "../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 200
DATASETS:
  TRAIN:
  - birds_train
  TEST:
  - birds_val
TEST:
  EVAL_PERIOD: 1000
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (2000, )
  MAX_ITER: 3000
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    ENABLED: True
  AMP:
    ENABLED: True