_BASE_: "../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 120
DATASETS:
  TRAIN:
  - dogs_train
  TEST:
  - dogs_val
TEST:
  EVAL_PERIOD: 1000
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.002
  STEPS: (2000, )
  MAX_ITER: 5000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    ENABLED: True
  AMP:
    ENABLED: True