_BASE_: "../COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ('voc_train',)
  TEST: ('voc_test',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (2000, 16000)
  MAX_ITER: 3000  # 17.4 epochs
  WARMUP_ITERS: 100